/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ssai_integrand_ipc_FifoIPCMessenger */

#ifndef _Included_com_ssai_integrand_ipc_FifoIPCMessenger
#define _Included_com_ssai_integrand_ipc_FifoIPCMessenger
#ifdef __cplusplus
extern "C" {
#endif
#undef com_ssai_integrand_ipc_FifoIPCMessenger_MESSAGE_LENGTH_SIZE
#define com_ssai_integrand_ipc_FifoIPCMessenger_MESSAGE_LENGTH_SIZE 8L
/*
 * Class:     com_ssai_integrand_ipc_FifoIPCMessenger
 * Method:    makeFifo
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ssai_integrand_ipc_FifoIPCMessenger_makeFifo
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
